title: Code with Decker 
description: Learn programming like I did!
theme: just-the-docs

url: https://ayersdecker.github.io/Code-Blog/

search_enabled: true

aux_links:
  Template Repository: https://github.com/ayersdecker/Code-Blog
