title: Code with Decker 
description: Learn programming like I did!
theme: just-the-docs

url: https://ayersdecker.github.io/Code-Blog/

search_enabled: true

aux_links:
  "www.deckerayers.com":
    - "//www.deckerayers.com"
  "Decker's Github":
    - "//github.com/ayersdecker"



