title: Code with Decker 
description: Learn programming like I did!
theme: just-the-docs

url: https://ayersdecker.github.io/Code-Blog/

aux_links:
  Repository: https://ayersdecker.github.io/Code-Blog/
